name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file .docker/Dockerfile --tag debatent/tp-devops\ docker/
    - name: Docker Login
      uses: docker/login-action@v1.4.1
      run: docker push debatent/tp-devops
      with:
        username: ${{ secret.LOGIN_DOCKER }}
        password: ${{ secret.PASSWORD_DOCKER }}
