name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file .docker/Dockerfile --tag debatent/tp-devops
    - name: Docker Login
      uses: docker/login-action@v1.4.1
      with:
        username: ${{ secrets.LOGIN_DOCKER }}
        password: ${{ secrets.PASSWORD_DOCKER }}
    - name: Docker Push
      run: docker push debatent/tp-devops
 
